"""initialial commit new

Revision ID: 5aee9162b700
Revises: 
Create Date: 2025-01-05 17:58:36.566165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aee9162b700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INDEX_PRICE',
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=True),
    sa.Column('Name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Date', 'Ticker')
    )
    op.create_table('NASDAQ_HOLDINGS',
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Sector', sa.String(), nullable=True),
    sa.Column('Industry', sa.String(), nullable=True),
    sa.Column('CompanyName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Ticker')
    )
    op.create_table('SP500_HOLDINGS',
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Sector', sa.String(), nullable=True),
    sa.Column('Industry', sa.String(), nullable=True),
    sa.Column('CompanyName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Ticker')
    )
    op.create_table('SP500_STOCKS_PRICE',
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=True),
    sa.Column('Volume', sa.Integer(), nullable=True),
    sa.Column('StockSplits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Ticker', 'Date')
    )
    op.create_table('Users',
    sa.Column('User', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('LastName', sa.String(), nullable=True),
    sa.Column('Phone', sa.String(), nullable=True),
    sa.Column('Address', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('State', sa.String(), nullable=True),
    sa.Column('Zip', sa.String(), nullable=True),
    sa.Column('Country', sa.String(), nullable=True),
    sa.Column('Role', sa.String(), nullable=True),
    sa.Column('Active', sa.Integer(), nullable=True),
    sa.Column('Created', sa.Date(), nullable=True),
    sa.Column('Updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('User')
    )
    op.create_table('WatchListTickers',
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Ticker')
    )
    op.create_table('watchlist_association',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('ticker_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['WatchListTickers.Ticker'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.User'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_association')
    op.drop_table('WatchListTickers')
    op.drop_table('Users')
    op.drop_table('SP500_STOCKS_PRICE')
    op.drop_table('SP500_HOLDINGS')
    op.drop_table('NASDAQ_HOLDINGS')
    op.drop_table('INDEX_PRICE')
    # ### end Alembic commands ###
