"""add new table stock price

Revision ID: 876ea8453f7a
Revises: 5aee9162b700
Create Date: 2025-01-05 18:34:16.887924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876ea8453f7a'
down_revision = '5aee9162b700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('STOCKS_PRICE',
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=True),
    sa.Column('Volume', sa.Integer(), nullable=True),
    sa.Column('StockSplits', sa.Integer(), nullable=True),
    sa.Column('IndexName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Ticker', 'Date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('STOCKS_PRICE')
    # ### end Alembic commands ###
