"""Create initial tables

Revision ID: c6bbf136b68f
Revises: 
Create Date: 2025-01-05 13:15:13.736304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bbf136b68f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INDEX_PRICE',
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('Date', 'Ticker')
    )
    op.create_table('NASDAQ_HOLDINGS',
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Sector', sa.String(), nullable=True),
    sa.Column('Industry', sa.String(), nullable=True),
    sa.Column('CompanyName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Ticker')
    )
    op.create_table('SP500_HOLDINGS',
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Sector', sa.String(), nullable=True),
    sa.Column('Industry', sa.String(), nullable=True),
    sa.Column('CompanyName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Ticker')
    )
    op.create_table('SP500_STOCKS_PRICE',
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=True),
    sa.Column('Volume', sa.Integer(), nullable=True),
    sa.Column('StockSplits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Ticker', 'Date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SP500_STOCKS_PRICE')
    op.drop_table('SP500_HOLDINGS')
    op.drop_table('NASDAQ_HOLDINGS')
    op.drop_table('INDEX_PRICE')
    # ### end Alembic commands ###
