"""add new table TickerInfo

Revision ID: cffae460f8dc
Revises: 403405bee04b
Create Date: 2025-01-11 10:43:06.014505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffae460f8dc'
down_revision = '403405bee04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TickerInfo',
    sa.Column('Ticker', sa.String(), nullable=False),
    sa.Column('CompanyName', sa.String(), nullable=True),
    sa.Column('Sector', sa.String(), nullable=True),
    sa.Column('Industry', sa.String(), nullable=True),
    sa.Column('Country', sa.String(), nullable=True),
    sa.Column('MarketCap', sa.Float(), nullable=True),
    sa.Column('PERatio', sa.Float(), nullable=True),
    sa.Column('ForwardPERatio', sa.Float(), nullable=True),
    sa.Column('Dividend', sa.Float(), nullable=True),
    sa.Column('ROE', sa.Float(), nullable=True),
    sa.Column('ROA', sa.Float(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Ticker')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TickerInfo')
    # ### end Alembic commands ###
